### ISSUE TITLE
FitBit as an add-on

### ISSUE THREAD

**Issue by albertpak** [gupta-ankit/FitgemOAuth2Rails#2]
Thank you for this gem - with the current set up - it allows users to create and sign up with their FitBit account. In my app, I currently have devise set up - users can sign up - but after sign up, after going to edit their account - i would like to add an option, something like `Add Fitbit` - so that I could pull user's data.

Found this before: http://postazure-blog.logdown.com/posts/259027-fitbit-api-rails-tutorial

Going to attempt to fit that into my app using your gem, but thought I'd ask also, just in case. :)

**Comment by gupta-ankit** [comment]
The tutorial is a bit old. It is using omniauth-fitbit version 1.x based which is based on earlier OAuth1.0 authentication supported by Fitbit. 

If you try the tutorial, my understanding is that it will stop working after April 12 (when OAuth1.0 will be discontinued).

For later use you will have to use omniauth-fitbit version 2.x, with some minor changes because with Fitbit OAuth 2 the API is scoped so that users can choose what data they choose to share with your application.

Otherwise, I think the rest of the stuff should work.

**Comment by albertpak** [comment]
I understand that the tutorial was for v1 of FitBit API - what I was looking for was a suggestion to a problem where I would want to add FitBit after user has signed up - i.e. to authorize my app to pull data for the user.

For example, user signs up (Devise) - gets an account - and then goes into their settings and clicks on `Connect with FitBit` and I invision that will allow my app to pull user's data afterwards.

**Comment by gupta-ankit** [comment]
Sorry, can't suggest anything there. I have always used Fitbit as my main login in my applications.
